### ISSUE TITLE
\item 中内容不换行

### ISSUE THREAD

**Issue by aoe-wyb** [Exception0x0194/SEU-CV#1]
\item 中内容不换行？
![image](https://github.com/user-attachments/assets/bf3904b1-a71b-4e82-a3d3-8bd653d35902)
内容超出一行能显示的字符之后，不自动进行换行处理。

**Comment by Exception0x0194** [comment]
的确没有对 `item` 等内容的换行进行设置，不过可以通过手动换行的方式解决这个问题（我自己也是这么干的）

```latex
\item 熟练使用 Python、Kotlin、JS 等程序语言，以及\\ % 添加了换行
      Vue.js、Flutter 等应用开发框架，技术栈丰富。
```

![图片](https://github.com/user-attachments/assets/9cea5a36-67ca-4866-9c50-613f558d7783)

**Comment by aoe-wyb** [comment]
确实，我尝试了很多方法，最好还是用“\\”
好使。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Exception0x0194 ***@***.***&gt;
发送时间: 2024年8月31日 23:49
收件人: Exception0x0194/SEU-CV ***@***.***&gt;
抄送: aoe-wyb ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Exception0x0194/SEU-CV] \item 中内容不换行 (Issue #1)
