### ISSUE TITLE
模板图片

### ISSUE THREAD

**Issue by Windrain7** [Exception0x0194/SEU-CV#2]
非常感谢您的模板！我想仿照着做一份我们学校的模板。我看您所参考的模板中都有着相似的花纹，只是背景颜色不同，这个操作是怎么实现的？以及banner-white.png是怎么制作的？十分感谢！

**Comment by Exception0x0194** [comment]
在这份模板中，使用的校徽图片来自[另一个 repo](https://github.com/seumxc/SEU-Logo)，包括背景的校徽和左上的 banner 图片；其他学校的校徽图片或许也可以从官网等官方渠道获取。虽然直接获取的图片颜色不太匹配（比如 banner 只有黑色），不过对于单色图片，使用简单的颜色映射就可以获取到颜色合适的图片（比如 banner-white.png）。

在上下两侧的装饰性图片是我在原模板的基础上，测量了原始图片的颜色（蓝色）和目标颜色（松针绿）之间的差值，进行 HSV 变换得到的。实际上使用尺寸类似、颜色匹配的图片应该都能得到不错的效果。
